name: Clone and Compress

on:
  push:
    branches:
      - main

jobs:
  clone-compress:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Read repository URL
      id: read-repo-url
      run: echo "::set-output name=url::$(cat repo.txt)"
      
    - name: Clone the specified repository
      run: git clone --recurse-submodules ${{ steps.read-repo-url.outputs.url }} cloned-repo

    - name: Update submodules
      run: |
        cd cloned-repo
        git submodule update --init --recursive

    - name: Compress the repository
      run: |
        sudo apt-get update
        sudo apt-get install -y zip
        zip -r9 compressed-repo.zip cloned-repo

    - name: Install GitHub CLI
      run: |
        sudo apt-get install -y gh
        gh auth login --with-token ${{ secrets.GITHUB_TOKEN }}

    - name: Create a release
      id: create_release
      run: |
        TAG_NAME="release-$(date +'%Y%m%d%H%M%S')"
        gh release create $TAG_NAME compressed-repo.zip --title "Automated Release $TAG_NAME" --notes "Automated release containing compressed repository."

    - name: Delete older releases
      run: |
        gh release list --limit 100 | tail -n +4 | while read -r line ; do
          TAG=$(echo $line | awk '{print $1}')
          gh release delete $TAG -y
        done
