name: Clone and Compress

on:
  push:
    branches:
      - main

jobs:
  clone-compress:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Read repository URL
      id: read-repo-url
      run: echo "::set-output name=url::$(cat repo.txt)"
      
    - name: Clone the specified repository
      run: git clone --recurse-submodules ${{ steps.read-repo-url.outputs.url }} cloned-repo

    - name: Update submodules
      run: |
        cd cloned-repo
        git submodule update --init --recursive

    - name: Compress the repository
      run: |
        sudo apt-get update
        sudo apt-get install -y zip
        zip -r9 compressed-repo.zip cloned-repo

    
    - uses: actions/checkout@v3
    - name: Create a Release
      uses: elgohr/Github-Release-Action@v5
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        title: Title
        workdir: ./

    - name: Delete older releases
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        releases=$(gh release list --limit 100)
        release_count=$(echo "$releases" | wc -l)
        if [ "$release_count" -gt 3 ]; then
          releases_to_delete=$(echo "$releases" | tail -n +4 | awk '{print $1}')
          for release in $releases_to_delete; do
            gh release delete $release -y
          done
        fi
